/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

/**
 *
 * @author ale
 */
public class menuAnalista extends javax.swing.JFrame {

    /**
     * Creates new form menuAnalista
     */
    public menuAnalista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistroAspirante = new javax.swing.JMenu();
        btnRegistroAspirante = new javax.swing.JMenuItem();
        menuSolicitudEntrevista = new javax.swing.JMenu();
        btnEntrevistaSolicitar = new javax.swing.JMenuItem();
        btnRegistrarEntrevista = new javax.swing.JMenuItem();
        MenuContrato = new javax.swing.JMenu();
        btnContratoRegistrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuRegistroAspirante.setText("Aspirante");
        menuRegistroAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRegistroAspiranteActionPerformed(evt);
            }
        });

        btnRegistroAspirante.setText("Registro Aspirtante");
        btnRegistroAspirante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAspiranteActionPerformed(evt);
            }
        });
        menuRegistroAspirante.add(btnRegistroAspirante);

        jMenuBar1.add(menuRegistroAspirante);

        menuSolicitudEntrevista.setText("Entrevista");

        btnEntrevistaSolicitar.setText("Solicitud Entrevista");
        btnEntrevistaSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrevistaSolicitarActionPerformed(evt);
            }
        });
        menuSolicitudEntrevista.add(btnEntrevistaSolicitar);

        btnRegistrarEntrevista.setText("Registrar Entrvista");
        btnRegistrarEntrevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEntrevistaActionPerformed(evt);
            }
        });
        menuSolicitudEntrevista.add(btnRegistrarEntrevista);

        jMenuBar1.add(menuSolicitudEntrevista);

        MenuContrato.setText("Contrato");

        btnContratoRegistrar.setText("Registrar Contrato");
        btnContratoRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratoRegistrarActionPerformed(evt);
            }
        });
        MenuContrato.add(btnContratoRegistrar);

        jMenuBar1.add(MenuContrato);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistroAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRegistroAspiranteActionPerformed

    }//GEN-LAST:event_menuRegistroAspiranteActionPerformed

    private void btnRegistroAspiranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAspiranteActionPerformed
        registroAspirante reasp = new registroAspirante();
        reasp.setVisible(true);
    }//GEN-LAST:event_btnRegistroAspiranteActionPerformed

    private void btnEntrevistaSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrevistaSolicitarActionPerformed
        solicitudEntrevista sole = new solicitudEntrevista();
        sole.setVisible(true);
    }//GEN-LAST:event_btnEntrevistaSolicitarActionPerformed

    private void btnContratoRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratoRegistrarActionPerformed
        registroContrato regCon = new registroContrato();
        regCon.setVisible(true);
    }//GEN-LAST:event_btnContratoRegistrarActionPerformed

    private void btnRegistrarEntrevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEntrevistaActionPerformed
        registroEntrevista regent = new registroEntrevista();
        regent.setVisible(true);
    }//GEN-LAST:event_btnRegistrarEntrevistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuAnalista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuAnalista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuContrato;
    private javax.swing.JMenuItem btnContratoRegistrar;
    private javax.swing.JMenuItem btnEntrevistaSolicitar;
    private javax.swing.JMenuItem btnRegistrarEntrevista;
    private javax.swing.JMenuItem btnRegistroAspirante;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuRegistroAspirante;
    private javax.swing.JMenu menuSolicitudEntrevista;
    // End of variables declaration//GEN-END:variables
}
